<a href="https://colab.research.google.com/github/CyberOutlier/BasicDeepLearning/blob/main/Multiple_in_out_puts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def w_sum(vec, matrix):
  output = 0
  assert(len(vec) == len(matrix))
  for i in range(len(vec)):
    output += vec[i] * matrix[i]
  return output

def ele_num(vec, matrix):
  output = [0, 0, 0]
  assert(len(output) == len(matrix))
  for i in range(len(vec)):
    output[i] += w_sum(vec, matrix[i])
  return output


def neural_network(input,weights):
  hidden = ele_num(input, weights[0])
  prediction = ele_num(hidden, weights[1])
  return prediction


weights1 = [ [0.1, 0.2, -0.1], #hid[0]
                  [-0.1,0.1, 0.9], #hid[1]
                  [0.1, 0.4, 0.1] ] #hid[2]

weights2 = [ [0.3, 1.1, -0.3], #hurt?
                   [0.1, 0.2, 0.0], #win?
                   [0.0, 1.3, 0.1] ]

weights = [weights1, weights2]

weather = [8.5, 9.5, 9.9, 9.0]

events = [0.65,0.8, 0.8, 0.9]

people = [1.2, 1.3, 0.5, 1.0]

#for i in range(len(weather)):
input = [weather[0], events[0], people[0]]
pred = neural_network(input, weights)
print(pred)

IndentationError: ignored

In [ ]:
 ih_wgt = [ [0.1, 0.2, -0.1], #hid[0]
           [-0.1,0.1, 0.9], #hid[1]
           [0.1, 0.4, 0.1] ] #hid[2]

           #hid[0] hid[1] hid[2]
hp_wgt = [ [0.3, 1.1, -0.3], #hurt?
           [0.1, 0.2, 0.0], #win?
           [0.0, 1.3, 0.1] ] #sad?

weights = [ih_wgt, hp_wgt]

def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

def vect_mat_mul(vect,matrix):
    assert(len(vect) == len(matrix))
    output = [0,0,0]
    for i in range(len(vect)):
        output[i] = w_sum(vect,matrix[i])
    return output

def neural_network(input, weights):
    hid = vect_mat_mul(input,weights[0])
    pred = vect_mat_mul(hid,weights[1])
    return pred

toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

# Input corresponds to every entry
# for the first game of the season.

input = [toes[0],wlrec[0],nfans[0]]
pred = neural_network(input,weights)

print(pred)

[0.21350000000000002, 0.14500000000000002, 0.5065]


In [4]:
import numpy as np

ih_wgt = np.array([ [0.1, 0.2, -0.1],
                  [-0.1, 0.1, 0.9],
                  [0.1, 0.4, 0.1] ]).T

hp_wgt = np.array([ [0.3, 1.1, -0.3],
                   [0.1, 0.2, 0.0],
                   [0.0, 1.3, 0.1] ]).T

weights = [ih_wgt, hp_wgt]

weather = [8.5, 9.5, 9.9, 9.0]

events = [0.65,0.8, 0.8, 0.9]

people = [1.2, 1.3, 0.5, 1.0]

def neural_network(input, weights):
  print(weights[0])
  hidden = input.dot(weights[0])
  print(hidden)
  prediction = hidden.dot(weights[1])
  return prediction

input = np.array([weather[3], events[3], people[3]])
print(input)
pred = neural_network(input, weights)
print(pred)

[9.  0.9 1. ]
[[ 0.1 -0.1  0.1]
 [ 0.2  0.1  0.4]
 [-0.1  0.9  0.1]]
[0.98 0.09 1.36]
[-0.015  0.116  0.253]


In [2]:
import numpy as np

#toes %win #fans
ih_wgt = np.array([ 
            [0.1, 0.2, -0.1], #hid[0]
            [-0.1,0.1, 0.9], #hid[1]
            [0.1, 0.4, 0.1]]).T #hid[2]


# hid[0] hid[1] hid[2]
hp_wgt = np.array([  
            [0.3, 1.1, -0.3], #hurt?
            [0.1, 0.2, 0.0], #win?
            [0.0, 1.3, 0.1] ]).T #sad?

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
  for i in range(len(weights)):
    hid = input.dot(weights[i])
    i += 1
    pred = hid.dot(weights[i])
    return pred


toes =  np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65,0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

for i in range(len(toes)):
  input = np.array([toes[i],wlrec[i],nfans[i]])
  pred = neural_network(input,weights)
  print(pred)

[0.2135 0.145  0.5065]
[0.204 0.158 0.53 ]
[-0.584  0.018 -0.462]
[-0.015  0.116  0.253]
